FORMAT: 1A
HOST: http://localhost:8080/turneroWeb

# TurneroMobile

Requerimiento Turnero y Cupón a través de Mobile

## Estado de Tienda  [/getStatusTienda]

### Obtener estado [POST]

Servicio permite obtener el estado de Atención de la Tienda solicitada

#### Parametros de Entrada 

Local : de largo de 4 digitos

#### Parametros de Salida 

Respuesta : Objeto con propiedades codigo y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

Status : ABIERTA / CERRADA

+ Request (application/json)

        {
            "local": "Identificacion del local"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "STATUS OK"
            },
            "status": "ABIERTA"
        }


## Estado de Turnero  [/getStatus]

### Obtener estado [POST]

Servicio permite obtener el estado del Turnero del local solicitado

#### Parametros de Entrada 

Local : de largo de 4 digitos

#### Parametros de Salida 

Respuesta : Objeto con propiedades codigo y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

Status : ACTIVO / DESACTIVADO

+ Request (application/json)

        {
            "local": "Identificacion del local"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "STATUS OK"
            },
            "status": "ACTIVO"
        }
        

## Número de Atención [/getNumeroAtencion]

### Obtener Número de Atención [POST]

Servicio permite obtener un número de Atención del local solicitado

#### Parametros de Entrada 

Local : de largo de 4 digitos
rutCliente : sin formato (sin puntos ni guiones)

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

numeroAtencion : Número de Atención entregado por el negocio al cliente que lo solicita

+ Request (application/json)

        {
            "local": "Identificacion del local",
            "rutCliente": "Identificacion del Cliente"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "NUMERO ATENCION OK"
            },
            "numeroAtencion": "V0001"
        }

## Reactivar Número de Atención [/setReactivarNumeroAtencion]

### Reactivar Número de Atención [POST]

Servicio permite reactivar un número de Atención solicitado con anterioridad por el cliente

#### Parametros de Entrada 

Local : de largo de 4 digitos
rutCliente : sin formato (sin puntos ni guiones)

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

numeroAtencion : Número de Atención 

+ Request (application/json)

        {
            "local": "Identificacion del local",
            "rutCliente": "Identificacion del Cliente"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "NUMERO ATENCION REACTIVADO OK"
            },
            "numeroAtención": "V0001"
        }

## Cancelar Número de Atención [/setCancelarNumeroAtencion]

### Cancelar Número de Atención [POST]

Servicio permite cancelar un número de Atención solicitado con anterioridad por el cliente

#### Parametros de Entrada 

Local : de largo de 4 digitos
rutCliente : sin formato (sin puntos ni guiones)
numeroAtencion : Número de Atención entregado previamente por la aplicación 

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación


+ Request (application/json)

        {
            "local": "Identificacion del local",
            "rutCliente": "Identificacion del Cliente",
            "numeroAtencion": "V0001"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "NUMERO ATENCION CANCELADO OK"
            }
        }
        
        
## Obtener Cupones del Cliente [/getCupones]

### Obtener cupones [POST]

Servicio permite solicitar un listado con los cupones disponibles por el Cliente

#### Parametros de Entrada 

rutCliente : sin formato (sin puntos ni guiones)

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación 

Cupones : listado con los cupones disponibles

+ Request (application/json)

        {
            "local": "Identificacion del local",
            "rutCliente": "Identificacion del Cliente",
            "numeroAtencion": "V0001"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "NUMERO ATENCION CANCELADO OK"
            }
            "cupones" : [
                  {
                     "rutCliente":"9475050-4"
                    ,"nombreCliente": "Liliana"
                    ,"apellidoCliente": "Villaroel"
                    ,"fechaVencimiento":"2018-06-08"
                    ,"nombre_tienda":"FALABELLA LYON"
                    ,"numero_cupon":990000000000001802011812311090830131713352
                    ,"estado":"disponible"
                  },
                  {
                     "rutCliente":"9475050-4"
                    ,"nombreCliente": "Liliana"
                    ,"apellidoCliente": "Villaroel"
                    ,"fechaVencimiento":"2018-06-08"
                    ,"nombre_tienda":"FALABELLA LYON"
                    ,"numero_cupon":990000000000001802011812311090830131713352
                    ,"estado":"disponible"
                  }
                ]
        }