FORMAT: 1A
HOST: http://localhost:8080/turneroWeb

# TurneroMobile

Requerimiento Turnero y Cupón a través de Mobile

## Estado de Tienda  [/getStatusStore]

### Obtener estado de la Tienda [POST]

Servicio permite obtener el estado de Atención de la Tienda solicitada

#### Parametros de Entrada 

channel : canal

source : fuente

country : pais

local : de largo de 4 digitos

#### Parametros de Salida 

Respuesta : Objeto con propiedades codigo y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

StatusStore : ABIERTA / CERRADA

hourOpen : Hora de Apertura (24H)

hourClose : Hora de Cierre (24H)

turneros : Lista con la ubicacion y estado de los turneros

ubication : !!!! POR DETERMINAR !!!

location : !!!! POR DETERMINAR !!!

status : Estado del turnero

+ Request (application/json)

        {
            "channel": "Identificacion del canal",
            "source": "Identificacion de la fuente",
            "country": "Identificacion del pais",
            "local": "Identificacion del local"
        }

+ Response 200 (application/json)

        {
            "response": {
                "code": "OK",
                "message": "STATUS OK"
            },
            "statusStore": "ABIERTA"
            "hourOpen": "09:00:00",
            "hourClose": "20:00:00" 
            "turneros" : [{
                "ubication" : "",
                "location"  : "",
                "status"    : "ACTIVO"
            },{
                "ubication" : "",
                "location"  : "",
                "status"    : "ACTIVO"
            }]
        }


## Estado de Turnero  [/getStatusTurnero]

### Obtener estado [POST]

Servicio permite obtener el estado del Turnero del local solicitado

#### Parametros de Entrada 

channel : canal

source : fuente

country : pais

local : de largo de 4 digitos

#### Parametros de Salida 

Respuesta : Objeto con propiedades codigo y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

status : ACTIVO / DESACTIVADO

ubication : !!!! POR DETERMINAR !!!

location : !!!! POR DETERMINAR !!!

status : Estado del turnero

+ Request (application/json)

        {
            "channel": "Identificacion del canal",
            "source": "Identificacion de la fuente",
            "country": "Identificacion del pais",
            "local": "Identificacion del local"
        }

+ Response 200 (application/json)

        {
            "response": {
                "code": "OK",
                "message": "STATUS OK"
            },
            "status": "ACTIVO",
            "ubication" : "",
            "location"  : ""
        }
        

## Número de Atención [/getAttentionNumber]

### Obtener Número de Atención [POST]

Servicio permite obtener un número de Atención del local solicitado

#### Parametros de Entrada 

channel : canal

source : fuente

country : pais

local : de largo de 4 digitos

turneroInfo : informacion de turnero

clientID : Rut del Cliente, sin formato (sin puntos ni guiones)

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

numeroAtencion : Número de Atención entregado por el negocio al cliente que lo solicita


+ Request (application/json)

        {
            "channel": "Identificacion del canal",
            "source": "Identificacion de la fuente",
            "country": "Identificacion del pais",
            "local": "Identificacion del local",
            "turneroInfo" : {
                                "ubication" : "",
                                "location"  : ""
                            },
            "clientID": "Identificacion del Cliente"
        }

+ Response 200 (application/json)

        {
            "response": {
                "code": "OK",
                "message": "NUMERO ATENCION OK"
            },
            "attentionNumber": "V0001"
        }

## Reactivar Número de Atención [/setActivateAttentionNumber]

### Reactivar Número de Atención [POST]

Servicio permite reactivar un número de Atención solicitado con anterioridad por el cliente

#### Parametros de Entrada 

channel : canal

source : fuente

country : pais

local : de largo de 4 digitos

clientID : RUT del Cliente, sin formato (sin puntos ni guiones)

attentionNumber: numero de atencion

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación

numeroAtencion : Número de Atención 


+ Request (application/json)

        {
            "channel": "Identificacion del canal",
            "source": "Identificacion de la fuente",
            "country": "Identificacion del pais",
            "local": "Identificacion del local",
            "clientID": "Identificacion del Cliente"
            "attentionNumber": "Numero de Atencion"
        }

+ Response 200 (application/json)

        {
            "response": {
                "code": "OK",
                "message": "NUMERO ATENCION REACTIVADO OK"
            },
            "attentionNumber": "V0001",
            "numberAttemps": 0
        }

## Cancelar Número de Atención [/setCancelAttentionNumber]

### Cancelar Número de Atención [POST]

Servicio permite cancelar un número de Atención solicitado con anterioridad por el cliente

#### Parametros de Entrada 

Local : de largo de 4 digitos

clientID :  Rut del Cliente, sin formato (sin puntos ni guiones)

attentionNumber : Número de Atención entregado previamente por la aplicación 

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación



+ Request (application/json)

        {
            "local": "Identificacion del local",
            "clientID": "Identificacion del Cliente",
            "attentionNumber": "V0001"
        }

+ Response 200 (application/json)

        {
            "respuesta": {
                "codigo": "OK",
                "mensaje": "NUMERO ATENCION CANCELADO OK"
            }
        }
        
        
## Obtener Cupones de Descuento del Cliente [/getCoupons]

### Obtener cupones [POST]

Servicio permite solicitar un listado con los cupones disponibles por el Cliente

#### Parametros de Entrada 

clientID : RUT del cliente, sin formato (sin puntos ni guiones)

#### Parametros de Salida 

Respuesta : Objeto con propiedades código y mensaje. Si el codigo es distinto de OK, se debe suponer que el mensaje 
es un error controlado por la aplicación 

coupons : Listado con los cupones disponibles

firstName : Nombre del cliente

lastName : Apellido del cliente

pactedDate : Fecha pactada

validDays : Días validos del cupon asignados por país

storeName : Nombre de la tienda

cuponNumber : Número del cupon

status : Estado del cupon

discountCoupon : Valor de descuento del cupon

promotionDesc : Descripción de la promoción

promotionCode : Código de la promoción


+ Request (application/json)

        {
            "clientID": "Identificacion del Cliente",
        }

+ Response 200 (application/json)

        {
            "response": {
                "code": "OK",
                "message": "NUMERO ATENCION CANCELADO OK"
            },
            "firstName": "Liliana",
            "lastName": "Villaroel",
            "coupons" : [
                  {
                    ,"pactedDate":"2018-06-08",
                    ,"validDays" : 3,
                    ,"storeName":"FALABELLA LYON",
                    ,"cuponNumber": "990000000000001802011812311090830131713352",
                    ,"status":"disponible",
                    ,"discountCoupon": 20,
                    ,"promotionDesc" : "de descuento en vestuario Hombre, Mujer y Niños",
                    ,"promotionCode" : 1090831
                  },
                  {
                    ,"expiredDate":"2018-06-08",
                    ,"storeName":"FALABELLA LYON",
                    ,"cuponNumber" : "990000000000001802011812311090830131713352",
                    ,"status":"disponible",
                    ,"discountCoupon": 20,
                    ,"promotionDesc" : "de descuento en vestuario Hombre, Mujer y Niños",
                    ,"promotionCode" : 1090831
                  }
                ]
        }